version: '3'

services:

  php-apache:
    # image: 'php:7.4-apache'
    container_name: e-nota
    build: dockerfiles/php
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
    restart: always