version: '3'

services:

  php-apache:
    container_name: e-nota
    build: dockerfiles/php
    links:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_NAME: "database"
      DB_USER: "user"
      DB_PASS: "pass"
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    restart: always

  # Banco de dados para testes
  db:
    container_name: mysql-server
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - 3306:3306
    restart: always