version: '3'

services:

  # Banco de dados para testes
  # db:
  #   container_name: mysql-server
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "root"
  #     MYSQL_DATABASE: "database"
  #     MYSQL_USER: "user"
  #     MYSQL_PASSWORD: "pass"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./db/mysql:/var/lib/mysql
  #   restart: always

  php-apache:
    container_name: e-nota
    build: dockerfiles/php
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - db
    volumes:
      - ./:/var/www/html
    restart: always